// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRpgqw1RT6FTO0jKqL3Ewsolsb9qi0Yco',
    appId: '1:954890287596:web:ec90caaf550d42bab028c9',
    messagingSenderId: '954890287596',
    projectId: 'root2route-e43e0',
    authDomain: 'root2route-e43e0.firebaseapp.com',
    storageBucket: 'root2route-e43e0.firebasestorage.app',
    measurementId: 'G-LDHK4F6H2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPrnRTHB9HZffuSTB0_-pGFHcDQbK6yjE',
    appId: '1:954890287596:android:6c662c8a431a166db028c9',
    messagingSenderId: '954890287596',
    projectId: 'root2route-e43e0',
    storageBucket: 'root2route-e43e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_mdF3JRxZegxLhXQGR9nUWk6JZqtFnCE',
    appId: '1:954890287596:ios:70fcfd1af619406cb028c9',
    messagingSenderId: '954890287596',
    projectId: 'root2route-e43e0',
    storageBucket: 'root2route-e43e0.firebasestorage.app',
    iosBundleId: 'com.example.root2route',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_mdF3JRxZegxLhXQGR9nUWk6JZqtFnCE',
    appId: '1:954890287596:ios:70fcfd1af619406cb028c9',
    messagingSenderId: '954890287596',
    projectId: 'root2route-e43e0',
    storageBucket: 'root2route-e43e0.firebasestorage.app',
    iosBundleId: 'com.example.root2route',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRpgqw1RT6FTO0jKqL3Ewsolsb9qi0Yco',
    appId: '1:954890287596:web:31e3ff64568750c9b028c9',
    messagingSenderId: '954890287596',
    projectId: 'root2route-e43e0',
    authDomain: 'root2route-e43e0.firebaseapp.com',
    storageBucket: 'root2route-e43e0.firebasestorage.app',
    measurementId: 'G-2T179N4SSM',
  );
}
